### ISSUE TITLE
Moded Minecarft Issues (Actually that's a general issue)

### ISSUE THREAD

**Issue by Blunder-G** [2mal3/No-Lag-Datapack#2]
You've heard of the Ice and Fire mode. The mod that adds those huge dragons. I love watching dragons fly, but because of NoLag freezes all entities, it is possible to see dragons floating in the air. To prevent this, I have to turn off EntityFreezing, this time those stupid zombies are damaging the game's performance.

I have a suggestion to prevent this: Assigning a whitelist file inside the Datapack folder. 

Ex picture (just in case):
![example](https://user-images.githubusercontent.com/56030297/123252651-33703600-d4f5-11eb-896a-9c2aa049bec3.PNG)

**Comment by 2mal3** [comment]
Finally, a person who uses the GitHub Issues :).

Actually, there is already an internal whitelist in the code, it's just hard to find. The whitelist is located at **data/2mal3/tags/entity_types/nola/ignore.json** in the datapack, there you can easily add new entity types in json format to be ignored by the datapack. For example, if you would add all the dragons from the ice and fire mod, 
```
{
  "replace": false,
  "values": [
    "#2mal3:nola/bosses",
    "#2mal3:nola/aligned",
    "minecraft:player",
    "minecraft:area_effect_cloud",
    "minecraft:command_block_minecart",
    "minecraft:marker"
  ]
}
```
would become
```
{
  "replace": false,
  "values": [
    "#2mal3:nola/bosses",
    "#2mal3:nola/aligned",
    "minecraft:player",
    "minecraft:area_effect_cloud",
    "minecraft:command_block_minecart",
    "minecraft:marker",
    "iceandfire:fire_dragon",
    "iceandfire:ice_dragon",
    "iceandfire:lightning_dragon"
  ]
}
```
(The end dragon is already ignored by default).

**Comment by Blunder-G** [comment]
Thanks! :)
