### ISSUE TITLE
Items get deleted while lag clear

### ISSUE THREAD

**Issue by M4th3M1tW** [2mal3/No-Lag-Datapack#3]
Hey there!

We installed the datapack on our 1.17 server. The problem we found is that items will get deleted when lag clear is executed. So after one of us died all of his item were deleted. I found that the item should get ignored by lag clear and just get deleted by custom item despawn, but we can't figure out why the items get deleted. 

Is there by any chance to get help or a fix?

Greetings!

**Comment by 2mal3** [comment]
Thanks for the report, I hadn't thought about that. I will exclude items from lag clears in the next update.
