### ISSUE TITLE
Confusing on which version to install

### ISSUE THREAD

**Issue by KualaBear** [2mal3/No-Lag-Datapack#4]
Found your data pack and thought it was really amazing!
I was wondering if it could be more organized on which version to download for because the zip files that you release are confusing because I don't know which version is the latest zip file.

**Comment by 2mal3** [comment]
Thanks for the info.
In general, I always recommend downloading the latest version of the datapack, i.e. the one shown on the main GitHub page on the right (currently v2.4.4).
But I can definitely display that more prominently.
